### PR TITLE
adding all calc operators

### PR DESCRIPTION
**Pull request by gaetbout**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

## What is the current behavior?

Resolves: #239 

## Other information

As i128 doesn't support div operation yet, I had to do some tricks.
Would be better to refactor it once i128 supports divmod
We need to make sure that max and min i128 are correct.
I asked in discord, better to wait for a confirmation.

### CODE REVIEW

**Comment by gaetbout** [comment]
@abdelhamidbakhta 
Read carefully the **Other information** section please 🙏

**Comment by zarboq** [comment]
Hey @gaetbout did you get updates for max and min int ?

Else PR looks good :rocket: Can you add a comment on top of the file with a TODO to update when i128 support division ?

**Comment by gaetbout** [comment]
hey @zarboq 
Not yet, but I can find it out by writing a quick test that'll (sub)overflow it.
I'll add that TODO comment, also need to make a quick review of myself. Will do that later today

**Comment by gaetbout** [comment]
@abdelhamidbakhta 
safe for merging now, did a test to make sure those are the correct min/max values

**Pull request merged**
