### PR TITLE
Feat: Completed Implementation of `role_store` contract. 

### PR DESCRIPTION
**Pull request by ametel01**
## Summary

Implemented `role_store` and added corresponding tests.

## Labels

- [x] Feature

## Issue Resolved

Resolves: #432 

## New Behavior

The new implementation mimics the behavior of the Solidity version but avoids using arrays in storage. Instead, `role_members_count` and `roles_count` track the total number of writes rather than the actual instance count. This is because deleting a `<key, value>` pair sets the `value` to `zero()` rather than removing it. To manage storage efficiently, the algorithm checks existing keys from 0 to the current storage count during insertion. If a `zero()` value is found, that key is reused; otherwise, a new key-value pair is created and the key count is incremented.

## Breaking Changes

None.

## Additional Info

N/A

### CODE REVIEW

**Review by zarboq — CHANGES_REQUESTED** [review]
Nice, could you just rename  some test to follow our test naming rules

Like in the first test -> `given_normal_conditions_when_revoke_role_then_works`

**Comment by ametel01** [comment]
> Nice, could you just rename some test to follow our test naming rules
> 
> Like in the first test -> `given_normal_conditions_when_revoke_role_then_works`

renamed tests

**Comment by zarboq** [comment]
Sorry I wasn't clear but the test you renamed was the one with good naming :)

Rename other tests following the same pattern (`given_...`)

**Comment by ametel01** [comment]
> Sorry I wasn't clear but the test you renamed was the one with good naming :)
> 
> Rename other tests following the same pattern (`given_...`)

done

**Review by Sk8erboi84 — APPROVED** [review]

**Review by Sk8erboi84 — APPROVED** [review]

**Review by Sk8erboi84 — APPROVED** [review]

**Review by zarboq — APPROVED** [review]

**Pull request merged**
