### PR TITLE
🔥 Remove chain module

### PR DESCRIPTION
**Pull request by Bal7hazar**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Refactoring (no functional changes, no API changes)

## What is the current behavior?

Resolves: #343 

## What is the new behavior?

Chain module has been removed.

## Does this introduce a breaking change?

Internal breaking changes.

## Other information

Workload: 1h

### CODE REVIEW

**Review by abdelhamidbakhta — DISMISSED** [review]
Lgtm

**Review by abdelhamidbakhta — CHANGES_REQUESTED** [review]
Please update the book

**Comment by Bal7hazar** [comment]
@abdelhamidbakhta 

I go this way if you are ok:

https://github.com/keep-starknet-strange/satoru/issues/343#issuecomment-1711864880

**Comment by Bal7hazar** [comment]
> Please update the book

@abdelhamidbakhta There are no Chain page if I'm not wrong

**Review by abdelhamidbakhta — APPROVED** [review]
Lgtm

**Pull request merged**
