### PR TITLE
Improve tests of position_utils library.

### PR DESCRIPTION
**Pull request by MavericksFive**
# Pull Request type

- Testing
- Other: Refactoring of the update_open_interest() function

## What is the current behavior?

The testing module position_utils should be improved.

## What is the new behavior?

New tests implemented, and they are all passing. The tests implemented are the following:

- test_is_position_liquiditable_below_min_collateral_leverage
- test_is_position_liquiditable_valid_position
- test_is_position_liquiditable_below_min_collateral
- test_is_position_liquiditable_negative_remaining_collateral_usd
- test_update_open_interest
- test_handle_referral
- test_update_total_borrowing

## Other information

Testing is still needed to be done on the following functions: 

- will_collateral_be_sufficient()
- update_funding_and_borrowing_state()

### CODE REVIEW

**Review by zarboq — CHANGES_REQUESTED** [review]
Great ! Left some comments. Are you planning to complete missing tests ?

**Comment by MavericksFive** [comment]
Hey Zarboq, sorry for the late answer... Will update it!

**Comment by MavericksFive** [comment]
> Great! Left some comments. Are you planning to complete the missing tests?


Hey Zarboq, sorry for the late answer... Will update it! I don't have time to complete the missing tests... Do you want me to create an issue?

**Comment by zarboq** [comment]
No worries :) Yes you can create an issue

**Review by zarboq — APPROVED** [review]

**Pull request merged**
